[package]
name = "rust"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"] # Compile this crate to a dynamic C library.

[dependencies]
bincode = { version = "2.0.1", features = ["serde"] }
godot = "0.3.1"
